name: Lint

on:
  push:
    branches:
      - main
    paths:
      - 'src/***'

jobs:
  lint:
    name: Run compiler/linter
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run tsc
        run: npx tsc

      - name: Run ESLint
        run: npx eslint --ext .ts,.cjs,.mjs lib/app/src
